language: java
sudo: required

addons:
  postgresql: "9.4"

before_install:
  - sudo free -m -t
  - date
  - sudo rm /etc/mavenrc
  - export MAVEN_OPTS="-Dmaven.repo.local=/home/travis/.m2/repository -Xmx1024M -XX:MaxPermSize=256m"
  -     echo "########################"
  - whoami
  - java -version
  - pwd
  - mvn help:system
  - export FS=`pwd`
  - sudo apt-get install -qq cloc
  -     echo "########################"
  - cloc ../
  -     echo "########################"

install:
  - sudo free -m -t
  - date
  - echo "Update settings"
  - cd $FS/utilities/project_helpers
  - sed -i'' 's/tomcat.(TOMCAT_VERSION)/travis/' ./config/variable.makefile.example
  - sed -i'' 's/lr.common.theme = /lr.common.theme = \/tmp\/dspace/' ./config/local.conf.dist
  - sed -i'' 's/dspace.install.dir = /dspace.install.dir = \/tmp\/dspace/' ./config/local.conf.dist
  - cd $FS/utilities/project_helpers/config
  - cp local.conf.dist ../sources/local.properties
  - cd $FS/utilities/project_helpers/scripts
  - echo "Creating dspace DB user and initialising databases"
  - sudo -u postgres createuser --superuser dspace
  - make create_databases
  - echo "Installing prerequisites"
  - make install_libs
  - make new_deploy | grep -v "Download"
  - make print_message

script:
  - sudo free -m -t
  - date
  - make test_dspace_database
  - make test_utilities_database
  - cd $FS/ && mvn -Dmaven.test.skip=false -Dtest=cz.cuni.mff.ufal.dspace.**.*Test,cz.cuni.mff.ufal.*Test -DfailIfNoTests=false test | grep -v "Download"

script:
  - sudo free -m -t
  - date
  - cd $FS/utilities/project_helpers/scripts
  - make tests
  - #make selenium_tests || echo "Tests failed"
