language: java
sudo: required

addons:
  postgresql: "9.4"

before_install:
  - sudo free -m -t
  - date
  - sudo rm /etc/mavenrc
  - export MAVEN_OPTS="-Dmaven.repo.local=/home/travis/.m2/repository -Xmx512M -XX:MaxPermSize=256m"
  -     echo "########################"
  - whoami
  - java -version
  - pwd
  - mvn help:system
  - export FS=`pwd`
  - sudo apt-get install -qq cloc
  -     echo "########################"
  - cloc ../
  -     echo "########################"

install:
  - sudo free -m -t
  - date
  - echo "Update settings"
  - cd $FS/utilities/project_helpers
  - sed -i'' 's/tomcat.(TOMCAT_VERSION)/travis/' ./config/variable.makefile.example
  - sed -i'' 's/lr.common.theme = /lr.common.theme = \/tmp\/dspace/' ./config/local.conf.dist
  - sed -i'' 's/dspace.install.dir = /dspace.install.dir = \/tmp\/dspace/' ./config/local.conf.dist
  - cd $FS/utilities/project_helpers/config
  - cp local.conf.dist ../sources/local.properties
  - cd $FS/utilities/project_helpers/scripts
  - echo "Creating dspace DB user and initialising databases"
  - sudo -u postgres createuser --superuser dspace
  - sudo free -m -t
  - make create_databases
  - sudo free -m -t
  - echo "Installing prerequisites"
  - make install_libs
  - sudo free -m -t
  - #make new_deploy | grep -v "Download"
  - #make compile | grep -v "Download"
  - cd /home/travis/build/ufal/lindat-dspace/utilities/project_helpers/scripts/../sources 
  - mvn clean package -Dassembly.ignorePermissions=true -Denforcer.skip=true -Denv=local -Dmaven.test.skip=true -P 'xpdf-mediafilter-support,!dspace-jspui,!dspace-sword-client,!dspace-swordv2,!dspace-sword,!dspace-lni,!dspace-rdf,!dspace-xmlui-mirage2,!generate-test-env' -B -V
  - sudo free -m -t
  - cd $FS/utilities/project_helpers/scripts
  - make fresh_install | grep -v "Download"
  - sudo free -m -t
  - make postinstall | grep -v "Download"
  - sudo free -m -t
  - make print_message

script:
  - sudo free -m -t
  - date
  - make test_dspace_database
  - make test_utilities_database
  - cd $FS/ && mvn -Dmaven.test.skip=false -Dtest=cz.cuni.mff.ufal.dspace.**.*Test,cz.cuni.mff.ufal.*Test -DfailIfNoTests=false test | grep -v "Download"

script:
  - sudo free -m -t
  - date
  - cd $FS/utilities/project_helpers/scripts
  - make tests
  - #make selenium_tests || echo "Tests failed"
